app/models/period.rb, app/models/period_day.rb, app/models/period_day_symptom.rb, app/models/symptom.rb, db/migrate/20220820133613_create_periods.rb, db/migrate/20220820134154_create_period_days.rb, db/migrate/20220820134303_create_period_day_symptoms.rb, db/migrate/20220820134819_create_symptoms.rb, db/migrate/20220820135458_add_symptoms_ref_to_period_day_symptoms.rb, db/schema.rb, test/models/period_day_symptom_test.rb, test/models/period_day_test.rb, test/models/period_test.rb, test/models/symptom_test.rb
=> Generated models

Gemfile.lock, app/controllers/period_day_symptoms_controller.rb, app/controllers/symptoms_controller.rb, config/routes.rb, test/controllers/period_day_symptoms_controller_test.rb, test/controllers/symptoms_controller_test.rb
Symptoms controllers and routes
=> controllers and routes

app/models/symptom.rb, app/views/symptoms/index.html.erb
=> symptom index

app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/controllers/period_day_symptoms_controller.rb
=> Updated controllers

app/controllers/symptoms_controller.rb, app/models/mood.rb, app/models/physical_symptom.rb, app/models/symptom.rb, app/views/symptoms/index.html.erb, db/migrate/20220820134819_create_symptoms.rb, db/migrate/20220823185042_drop_symptoms.rb, db/migrate/20220823191759_delete_symptoms.rb, db/migrate/20220823193200_drop_columns_from_periods.rb, db/migrate/20220823193635_drop_end_date_column_from_periods.rb, db/migrate/20220823194403_create_moods.rb, db/migrate/20220823194537_create_physical_symptoms.rb, db/migrate/20220823194719_add_mood_id_to_period_day_symptoms.rb, db/migrate/20220823195027_add_physical_symptoms_id_to_period_day_symptoms.rb, db/migrate/20220823195416_add_name_to_mood.rb, db/migrate/20220823200007_add_name_to_moods.rb, db/migrate/20220823200139_add_emoji_to_moods.rb, db/migrate/20220823200251_add_name_to_physical_symptoms.rb, db/schema.rb, test/models/mood_test.rb, test/models/physical_symptom_test.rb
=> Updated based on DB schema

db/migrate/20220823210226_add_start_date_to_period.rb, db/migrate/20220823210511_add_end_date_to_period.rb, db/schema.rb
=> Updated columns in Periods

app/controllers/moods_controller.rb, app/controllers/physical_symptoms_controller.rb, app/models/mood.rb, app/models/period_day_symptom.rb, app/views/physical_symptoms/index.html.erb, config/routes.rb, db/migrate/20220820134819_create_symptoms.rb, db/migrate/20220823185042_drop_symptoms.rb, db/migrate/20220823195416_add_name_to_mood.rb, db/seeds.rb, test/controllers/moods_controller_test.rb, test/controllers/physical_symptoms_controller_test.rb
Migration, physical symptoms seed, mood and PS controllers and veiw
=> migration fixed

app/controllers/flow_controller.rb, app/models/flow.rb, db/migrate/20220825191113_create_flows.rb, db/schema.rb, test/controllers/flow_controller_test.rb, test/models/flow_test.rb
added flow model and controller
=> added flow model and controller

app/views/physical_symptoms/index.html.erb
=> Changes to seed file

app/views/physical_symptoms/index.html.erb
Checkbox form for physical symptoms. Will work on the submit button later
=> checkbox form for physical symptoms

app/controllers/flow_controller.rb, app/controllers/flows_controller.rb, app/controllers/moods_controller.rb, app/views/flows/index.html.erb, app/views/moods/index.html.erb, config/routes.rb, db/seeds.rb
updated seed file and corresponding view pages
=> updated seed file and corresponding view pages

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/emoji.scss, app/controllers/period_day_symptoms_controller.rb, app/controllers/physical_symptoms_controller.rb, app/views/physical_symptoms/index.html.erb, config/routes.rb
physical symptoms controller and form
=> physical symtoms controller and form

app/controllers/flows_controller.rb, app/controllers/moods_controller.rb, app/controllers/physical_symptoms_controller.rb, app/views/flows/index.html.erb, app/views/moods/index.html.erb
Updated as discussed, followed Ruqiya's template and tested in local host
=> Added create button to mood and flow

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
=> Added burger menu

app/assets/stylesheets/components/_navbar.scss, app/controllers/flows_controller.rb, app/controllers/moods_controller.rb, app/controllers/period_day_symptoms_controller.rb, app/controllers/physical_symptoms_controller.rb, db/seeds.rb
=> Tweaks following team meet

db/migrate/20220903141553_add_flow_id_to_period_day_symptoms.rb, db/schema.rb
=> Updated schema and seed file

app/controllers/period_day_symptoms_controller.rb, config/routes.rb
Working on controller for PSD and Route changes
=> Working on controller for PSD 

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
=> Logo size and positioning fixed

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
Small tweak to logo and dropdown fonts to match Yulin's (font-family: "Nunito", "Helvetica", "sans-serif";)
=> Tweak to font

app/views/periods/index.html.erb
=> calendar working

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb
=> Added placeholder buttons and CSS on other buttons

app/controllers/pages_controller.rb, app/views/pages/home.html.erb, app/views/period_day_symptoms/index.html.erb, app/views/periods/_form.html.erb, app/views/periods/index.html.erb
=> Home-calender-sync

app/assets/stylesheets/components/_button.scss, app/views/shared/_footer.html.erb
Updated buttons as per stand up
=> Updated buttons

app/controllers/articles_controller.rb, app/models/article.rb, app/views/articles/index.html.erb, config/routes.rb, db/migrate/20220910110727_create_articles.rb, db/schema.rb, test/controllers/articles_controller_test.rb, test/models/article_test.rb
Added model, controller, view for content / articles page
=> Added articles mvc

app/controllers/periods_controller.rb, app/views/pages/home.html.erb, app/views/periods/_form.html.erb, app/views/shared/_footer.html.erb
=> redirect_to_symtoms_page

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_navbar.scss, app/views/articles/index.html.erb
=> Created cards for content page

app/controllers/period_day_symptoms_controller.rb, app/views/periods/index.html.erb, app/views/periods/show.html.erb, app/views/shared/_footer.html.erb
=> period-show-page

app/views/periods/show.html.erb
=> Delete period on summery page

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_navbar.scss, app/views/articles/index.html.erb, app/views/articles/show.html.erb, app/views/shared/_footer.html.erb
Created cards for articles pages
=> Created cards for index and show pages for content

app/assets/stylesheets/components/_card.scss
=> Updated padding on cards

app/controllers/reminders_controller.rb, app/models/reminder.rb, app/models/user.rb, app/views/reminders/index.html.erb, app/views/reminders/new.html.erb, config/routes.rb, db/migrate/20220912101439_create_reminders.rb, db/schema.rb, test/controllers/reminders_controller_test.rb, test/models/reminder_test.rb
Can create reminders, still wokring on displaying and deleting, but backend is done
=> start to reminders

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_calender.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/pages/_totm-show.scss, app/views/pages/home.html.erb, app/views/periods/index.html.erb
=> calendar css

app/assets/stylesheets/components/_calender.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/views/pages/home.html.erb, app/views/periods/index.html.erb
=> Home front end

app/assets/stylesheets/components/_index.scss
Not sure team.....undecided on background colour, I'll get some inspo from Dribbble and push something else tomorrow.
=> trying a blue background - will continue tweaking tomorrow

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
Removed reminders and reduced font size
=> removed reminders from drop down menu

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_calender.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_form_legend_clear.scss, app/views/pages/home.html.erb, app/views/periods/_form.html.erb, app/views/periods/new.html.erb
=> css add new period

app/assets/stylesheets/components/_calender.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss
=> Fixed footer and border repeat

public/404.html, public/500.html
=> Added error pages

app/assets/stylesheets/components/_article.scss, app/views/articles/index.html.erb, app/views/articles/show.html.erb, db/schema.rb
Styling updates to articles and article show page
=> Added styling to article show page and icons

app/assets/stylesheets/components/_article.scss, app/views/articles/show.html.erb
=> Tweaked photo

app/assets/stylesheets/components/_calender.scss, app/assets/stylesheets/components/_card.scss, app/views/pages/home.html.erb, app/views/simple_calendar/_calendar.html.erb, app/views/simple_calendar/_month_calendar.html.erb, app/views/simple_calendar/_week_calendar.html.erb
CSS on Calendar. Faded Prev/Next month dates. BG now transparent and height increased
=> CSS on Calendar

app/controllers/application_controller.rb, app/views/layouts/application.html.erb, app/views/offers/show.html.erb, app/views/periods/show.html.erb, config/config/meta.yml, config/initializers/default_meta.rb
Open graph meta tags and delete button on symptom summery page
=> Open graph meta tags 

app/assets/stylesheets/components/_article.scss, app/assets/stylesheets/components/_card.scss
Updated advice and article page to be responsive.
=> Responsive advice and article pages

app/assets/stylesheets/pages/_totm-show.scss, app/views/devise/sessions/new.html.erb
Tweaked login - still needs some styling (remember me checkbox isn't aligning nicely).
=> Tweaks to log in page styling
